-- Migration: Create registration table for PT Bridgestone Tire Indonesia
-- Created: 2026-07-27

CREATE TABLE IF NOT EXISTS bridgestone_incident_response_registration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  full_name TEXT NOT NULL,
  company_name TEXT NOT NULL,
  division_role TEXT NOT NULL,
  email TEXT,
  phone_number TEXT
);

ALTER TABLE bridgestone_incident_response_registration ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable insert for everyone" ON bridgestone_incident_response_registration;
CREATE POLICY "Enable insert for everyone" ON bridgestone_incident_response_registration
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable read access for authenticated users only" ON bridgestone_incident_response_registration;
CREATE POLICY "Enable read access for authenticated users only" ON bridgestone_incident_response_registration
  FOR SELECT USING (auth.role() = 'authenticated');
